### ISSUE TITLE
请问如何多卡推理以及多卡训练？

### ISSUE THREAD

**Issue by rainbowoldhorse** [ssbuild/rwkv_finetuning#3]
大佬你好，我一直未能找到支持多卡推理的参数，请问它在哪里呢？在lora训练里我发现MyTransformer中包含device_map参数，我将其设置为"auto"，但还是未能多卡推理，求指教

**Comment by ssbuild** [comment]
多卡推理例子较多 可以自行参考， 之后也会同步一个服务脚本。

**Comment by rainbowoldhorse** [comment]
谢谢大佬，目前代码中finetune训练和lora训练也不支持多卡吗？

**Comment by ssbuild** [comment]
https://github.com/ssbuild/rwkv_finetuning/blob/dev/args.MD

**Comment by rainbowoldhorse** [comment]
好的，谢谢大佬
