### ISSUE TITLE
Not recommended training set format

### ISSUE THREAD

**Issue by Pevernow** [ssbuild/rwkv_finetuning#7]
![image](https://github.com/ssbuild/rwkv_finetuning/assets/29888010/67378c2b-f5cf-4020-99f6-642f741eb71a)
This project adopts a strange training set format, which makes the official training set format of RWKV unusable.

May I ask if there is any solution?

Or provide a tool for converting dataset formats?

**Comment by ssbuild** [comment]
yes , it is on the way ...

**Comment by Pevernow** [comment]
Oh, thank you very much.

I am looking forward to the implementation of this feature.

**Comment by Pevernow** [comment]
By the way, considering that Qlora is mainly suitable for PCs with smaller graphics memory.

Do you have any plans to merge some of the features of this project into RWKV_ In Runner?

Graphical operations can effectively lower the threshold for QLora.

**Comment by ssbuild** [comment]
You make a valid point, but it's not something I excel at. Welcome everyone to contribute to open source.

**Comment by ssbuild** [comment]
the data struct you provice  is diffirent is prefix Q:  in q , and A:  in corpus ,   you can convet
 {
     "id": 0, "paragraph": [
         {
             "q": "Q:从南京到上海的路线\n\n",
             "a":  "A:你好，南京到上海的路线如下：1. 南京到上海，可以乘坐南京地铁1号线，在南京站乘坐轨道交通1号线。2. 南京到浦东机场，可以搭乘上海地铁1号，在陆家嘴站乘坐地铁1线，在浦东国际机场站乘坐机场快线，前往上海浦东国际机场。3. 上海到南京，可以换乘上海地铁2号线，从南京站换乘地铁2线，再从南京南站换乘地铁1路，然后到达上海站\n\n"
         }
     ]
 }

**Comment by Pevernow** [comment]
> the data struct you provice is diffirent is prefix Q: in q , and A: in corpus , you can convet { "id": 0, "paragraph": [ { "q": "Q:从南京到上海的路线\n\n", "a": "A:你好，南京到上海的路线如下：1. 南京到上海，可以乘坐南京地铁1号线，在南京站乘坐轨道交通1号线。2. 南京到浦东机场，可以搭乘上海地铁1号，在陆家嘴站乘坐地铁1线，在浦东国际机场站乘坐机场快线，前往上海浦东国际机场。3. 上海到南京，可以换乘上海地铁2号线，从南京站换乘地铁2线，再从南京南站换乘地铁1路，然后到达上海站\n\n" } ] }

There may be a problem here.

Because the text section of "q": "Q: Route from Nanjing to Shanghai n n" already has the prefix "Q:".

Normally, your data preprocessing program will add prefixes to it again.

The repetition of prefixes can affect the effectiveness of training.

**Comment by ssbuild** [comment]
you can choose TokenSupervision  or TokenUnSupervision , especially  TokenUnSupervision  is same as the way you provide , They are essentially the same。
and select TokenUnSupervision   , empty question , all data field fill answer , sliding paragraph window is same to chunks you provide.
