### ISSUE TITLE
不支持world模型吗？

### ISSUE THREAD

**Issue by gg22mm** [ssbuild/rwkv_finetuning#8]
支持world模型吗？ 我没看到有world词表： https://github.com/ssbuild/rwkv_finetuning/tree/dev/tools/rwkv4_infer

**Comment by ssbuild** [comment]
world 暂时不支持 ， 切词器变了，这两天抽时间，改下 tokenizer 就可以了。

**Comment by gg22mm** [comment]
好的。感谢回复~~   

大老不知道后面能不能用模型合并： 
如： https://github.com/iantbutler01/rwkv-raven-qlora-4bit-instruct/blob/main/merge.py
或：https://github.com/Blealtan/RWKV-LM-LoRA/blob/main/RWKV-v4neo/merge_lora.py

合并后就可以直接在闻达上使用 : https://github.com/wenda-LLM/wenda
那样非常方便~~

**Comment by ssbuild** [comment]
https://github.com/ssbuild/rwkv_finetuning/blob/33ac6a06b8338a76ff2b57162cc24477c4a027de/infer_lora_finetuning.py#L54

就算不支持合并， 手动改改wenda 的代码就行了吧， 很简单

**Comment by gg22mm** [comment]
嗯嗯，也是可以的。到时研究一下~~
